### ISSUE TITLE
cog segfault when WS::Instance::singleton().createClient()

### ISSUE THREAD

**Issue by Houqiqi** [Igalia/cog#592]
I'm using below release version:
cog-0.14.1
libwpe-1.14.1
wpebackend-fdo-1.14.2
wpewebkit-2.40.3

`static Instance* s_singleton;` has been effectively initialized in wpebackend-fdo-1.14.2/src/initialize-egl.cpp with below code, but it's strange that `s_singleton ` became NULL when later using it to createClient, which causes segfult.
Initialize process and this createClient process should be the same process, can anyone give me some advice why `s_singleton` is reset?
```
bool
wpe_fdo_initialize_for_egl_display(EGLDisplay display)
{
    if (!WS::Instance::isConstructed())
        WS::Instance::construct(std::unique_ptr<WS::ImplEGL>(new WS::ImplEGL));

    auto& instance = WS::Instance::singleton();
    return static_cast<WS::ImplEGL&>(instance.impl()).initialize(display);
}
```

The gdb log is as below:
```
Thread 1 "cog" received signal SIGSEGV, Segmentation fault.
WS::Instance::createClient (this=0x0) at /usr/src/debug/wpebackend-fdo/1.14.2-r0/src/ws.cpp:497
497	    if (!m_impl->initialized())
(gdb) bt
#0  WS::Instance::createClient (this=0x0) at /usr/src/debug/wpebackend-fdo/1.14.2-r0/src/ws.cpp:497
#1  0x0000fffff35d5810 in WebKit::WebProcessPool::platformInitializeWebProcess(WebKit::WebProcessProxy const&, WebKit::WebProcessCreationParameters&) ()
   from /usr/lib/libWPEWebKit-1.1.so.0
#2  0x0000fffff34a8cf4 in WebKit::WebProcessPool::initializeNewWebProcess(WebKit::WebProcessProxy&, WebKit::WebsiteDataStore*, WebKit::WebProcessProxy::IsPrewarmed) ()
   from /usr/lib/libWPEWebKit-1.1.so.0
#3  0x0000fffff34a9d5c in WebKit::WebProcessPool::createNewWebProcess(WebKit::WebsiteDataStore*, WebKit::WebProcessProxy::LockdownMode, WebKit::WebProcessProxy::IsPrewarmed, WebCore::CrossOriginMode) () from /usr/lib/libWPEWebKit-1.1.so.0
#4  0x0000fffff34aa38c in WebKit::WebProcessPool::processForRegistrableDomain(WebKit::WebsiteDataStore&, WebCore::RegistrableDomain const&, WebKit::WebProcessProxy::LockdownMode) () from /usr/lib/libWPEWebKit-1.1.so.0
#5  0x0000fffff346e390 in WebKit::WebPageProxy::launchProcess(WebCore::RegistrableDomain const&, WebKit::WebPageProxy::ProcessLaunchReason) ()
   from /usr/lib/libWPEWebKit-1.1.so.0
#6  0x0000fffff346f2a4 in WebKit::WebPageProxy::loadRequest(WebCore::ResourceRequest&&, WebCore::ShouldOpenExternalURLsPolicy, API::Object*) ()
   from /usr/lib/libWPEWebKit-1.1.so.0
#7  0x0000fffff352b250 in webkit_web_view_load_uri () from /usr/lib/libWPEWebKit-1.1.so.0
#8  0x0000aaaaaaaa6f1c in cog_launcher_create_view (self=<optimized out>, shell=<optimized out>) at /usr/src/debug/cog/0.14.1-r0/launcher/cog-launcher.c:328
#9  0x0000fffff0466670 in ?? () from /usr/lib/libffi.so.8
#10 0x0000fffff0465d74 in ?? () from /usr/lib/libffi.so.8
#11 0x0000fffff25f82d4 in g_cclosure_marshal_generic () from /usr/lib/libgobject-2.0.so.0
#12 0x0000fffff25f7998 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#13 0x0000fffff260cbcc in ?? () from /usr/lib/libgobject-2.0.so.0
#14 0x0000fffff2612a50 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#15 0x0000fffff26132f0 in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#16 0x0000fffff7f89bd8 in cog_shell_startup_base (shell=0xaaaaaab28870) at /usr/src/debug/cog/0.14.1-r0/core/cog-shell.c:168
#17 0x0000aaaaaaaa843c in cog_launcher_startup (application=<optimized out>) at /usr/src/debug/cog/0.14.1-r0/launcher/cog-launcher.c:363
#18 0x0000fffff25f5d64 in ?? () from /usr/lib/libgobject-2.0.so.0
#19 0x0000fffff25f7be0 in ?? () from /usr/lib/libgobject-2.0.so.0
#20 0x0000fffff26130a4 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#21 0x0000fffff26132f0 in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#22 0x0000fffff2767c54 in g_application_register () from /usr/lib/libgio-2.0.so.0
#23 0x0000fffff27681b4 in ?? () from /usr/lib/libgio-2.0.so.0
#24 0x0000fffff2768530 in g_application_run () from /usr/lib/libgio-2.0.so.0
#25 0x0000aaaaaaaa58f4 in main (argc=2, argv=0xfffffffffb98) at /usr/src/debug/cog/0.14.1-r0/launcher/cog.c:41
(gdb) 
```

**Comment by Houqiqi** [comment]
This seems like environment issue. Rebuild it and this issue is gone.
